version: "3.8"

services:
  psychemitherz:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/psychemitherz/Dockerfile
    environment:
      MIX_ENV: prod
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    networks:
      - webnet
    ports:
      - "4000:4000"
    command: /app/bin/psychemitherz start
networks:
  webnet:
    external: true
